# Generated by Django 3.2.8 on 2022-05-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journalweb', '0002_auto_20220519_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='submit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(upload_to='%m/%d/%y')),
            ],
        ),
    ]
