# Generated by Django 3.2.8 on 2022-05-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journalweb', '0003_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Picture',
            field=models.ImageField(blank=True, null=True, upload_to='Media'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
