# Generated by Django 3.2.8 on 2022-05-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journalweb', '0007_alter_projects_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project',
        ),
        migrations.AlterField(
            model_name='category',
            name='Name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_topic',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='projects',
            name='submitted_by',
            field=models.CharField(max_length=250),
        ),
    ]
