# Generated by Django 3.2.8 on 2022-05-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journalweb', '0008_auto_20220523_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
